FROM ubuntu:focal
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes make sudo equivs

ADD test/su /etc/pam.d/su
ADD test/sudoers /etc/sudoers

RUN groupadd test_group
RUN useradd --create-home --shell /bin/bash --group test_group test_user

ADD deploy.tar /home/test_user/opt
RUN chown --recursive --verbose test_user:test_group /home/test_user/opt
WORKDIR /home/test_user/opt

USER test_user

ENTRYPOINT [ "./init.sh" ]
