REPO=https://github.com/vim/vim.git
DEPENDENCIES=xorg-dev libgtk-3-dev python3-dev libncurses-dev silversearcher-ag python3-pip exuberant-ctags
PIP3_DEPENDENCIES=powerline-status
CONFIGURE_OPTS=--enable-python3interp --enable-gui=gtk3 --with-x

include ../std.makefile.defs
include ../git.makefile.defs
include ../base.makefile.defs
