APT_DEPENDENCIES=vim tmux pass aptitude rofi jq rsync atop irssi emacs
PACKAGE_URLS = https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

install:

include ../defs/base.makefile

